export const players=[
     {
        "id":1,
        "name":"Shoaib",
        "image":require('../assets/shoaib.jpeg') 
     },
     {
        "id":2,
        "name":"Hassan",
        "image":require('../assets/hassan.jpeg') 
     },
     {
        "id":3,
        "name":"Zain",
        "image":require('../assets/zain.jpeg') 
     },
     {
        "id":4,
        "name":"msyed",
        "image":require('../assets/msyed.jpeg') 
     }
]